<?php
/**
 * Data access layer for robots.txt stored content.
 *
 * All reads and writes to wp_options go through this class.
 *
 * @package Divit_RobotTXT
 * @since   1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Divit_RobotTXT_Options
 *
 * @since 1.0.0
 */
class Divit_RobotTXT_Options {

	/**
	 * The wp_options key used to store the robots.txt rules.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	const OPTION_KEY = 'divit_robottxt_rules';

	/**
	 * Retrieve stored robots.txt content.
	 *
	 * Returns an empty string if nothing has been saved yet.
	 *
	 * @since 1.0.0
	 *
	 * @return string
	 */
	public static function get_rules() {
		$value = get_option( self::OPTION_KEY, '' );

		return is_string( $value ) ? $value : '';
	}

	/**
	 * Sanitise and persist robots.txt content.
	 *
	 * @since 1.0.0
	 *
	 * @param string $raw Raw POST value (before wp_unslash).
	 * @return true|WP_Error True on success, WP_Error on validation failure.
	 */
	public static function save_rules( $raw ) {
		$prepared = Divit_RobotTXT_Validator::prepare( $raw );
		$result   = Divit_RobotTXT_Validator::validate( $prepared );

		if ( ! $result['valid'] ) {
			return new WP_Error(
				'divit_robottxt_invalid',
				implode( ' | ', $result['errors'] )
			);
		}

		update_option( self::OPTION_KEY, $prepared );

		return true;
	}

	/**
	 * Return the recommended robots.txt template.
	 *
	 * The Sitemap line uses the current site URL resolved at runtime
	 * so it is always accurate regardless of site migrations.
	 *
	 * @since 1.0.0
	 *
	 * @return string
	 */
	public static function get_default_template() {
		$sitemap_url = trailingslashit( get_site_url() ) . 'sitemap.xml';

		return implode(
			"\n",
			array(
				'# Recommended robots.txt for WordPress',
				'# Generated by Divit RobotTXT',
				'',
				'User-agent: *',
				'Disallow: /wp-admin/',
				'Allow: /wp-admin/admin-ajax.php',
				'',
				'Sitemap: ' . $sitemap_url,
			)
		);
	}
}
